# version: 2

# models:
#   - name: raw_price
#     description: ""
#     columns:
#       - name: id
#         description: ""
#         tests:
#           - unique
#           - not_null
#       - name: id
#         description: ""
#         tests:
#           - unique
#           - not_null